# Generated by Django 3.2.7 on 2021-09-28 15:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_author_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.book_image_file_path),
        ),
    ]
